---
# Jonathan Holloway <loadtheaccumulator@gmail.com>
# DESTROYS A CLUSTER - no takebacks (use with caution!!!)


- hosts: CLIENTS
  gather_facts: no
  remote_user: root

  vars_files:
    - "{{ varfile }}"

  tasks:
  - name: unmount the volume
    glusterclient: command=unmount mountpoint={{ mountpoint }}
    ignore_errors: yes
    tags:
      - unmount_volume


- hosts: MASTERNODE
  gather_facts: no
  remote_user: root

  vars_files:
    - "{{ varfile }}"

  tasks:
  - name: stop volume
    glustervolume: command=stop name={{ volumename }}
    ignore_errors: yes
    tags:
      - stop_volume

  - name: delete volume
    glustervolume: command=delete name={{ volumename }}
    ignore_errors: yes
    tags:
      - delete_volume

  - name: detach peers
    glusterpeer: command=detach name={{ item }}
    with_items:  groups['PEERS']
    ignore_errors: yes
    tags:
      - detach_peers


- hosts: NODES
  gather_facts: no
  remote_user: root

  vars_files:
    - "{{ varfile }}"

  vars:
    vgname_prefix: vg_gluster
    poolname_prefix: lv_pool
    lvname_prefix: lv_brick
    fslabel_prefix: brick
    mountpoint_prefix: "/bricks/fs_gluster"
    brickname: brick

  tasks:
  - name: auto destroy bricks
    glusterbrick: command=autodestroy
    register: num_bricks
    ignore_errors: yes
    tags:
      autodestroy_bricks


  # TUNED-ADM PROFILE
  - name: set tuned-adm profile
    shell: "tuned-adm profile default"
    when: skip_tuning is not defined
    ignore_errors: yes
    tags:
    - tuned-adm_profile_default


  # CONFIGURE SAMBA
  # TODO: ansiblefy these
  - name: chkconfig off samba
    service: name=smb enabled=no
    when: skip_samba is not defined
    ignore_errors: yes
    tags:
    - deconfig_samba

  - name: stop samba service
    service: name=smb state=stopped
    ignore_errors: yes
    when: skip_samba is not defined
    tags:
    - deconfig_samba

# TODO: add some logic to scramble root passwd or remove non-root user
  - name: deconfig samba user/pass
    shell: (echo "lkjsldedljsldj"; echo "lkjsldedljsldj" ) | smbpasswd -as {{ smb_user }}
    ignore_errors: yes
    when: skip_samba is not defined
    tags:
    - deconfig_samba


# TODO: move this to an include
- hosts: MASTERNODE
  gather_facts: no
  remote_user: root
  tasks:
  - name: show PV info
    command: pvs
    register: pvinfo

  - name: show VG info
    command: vgs
    register: vginfo

  - name: show LV info
    command: lvs
    register: lvinfo

  - name: show gluster volume info
    command: gluster volume info
    register: volinfo

  - debug: var=pvinfo.stdout_lines
  - debug: var=vginfo.stdout_lines
  - debug: var=lvinfo.stdout_lines
  - debug: var=volinfo.stderr

