---
# Jonathan Holloway <loadtheaccumulator@gmail.com>
# DESTROYS A GEOREP CASCADE CLUSTER - no takebacks (use with caution!!!)


# CLIENT - UNMOUNT VOLUME
- hosts: CLIENTS
  gather_facts: no
  remote_user: root

  vars_files:
    - "{{ varfile }}"

  tasks:
  - name: unmount the volume
    glusterclient: command=unmount mountpoint={{ mountpoint }}
    ignore_errors: yes
    tags:
      - unmount_volume

# THE GEO-REP STUFF
- hosts: IC_MASTERNODE
  gather_facts: no
  remote_user: root

  vars_files:
    - "{{ varfile }}"

  vars:
    master_volume_name: "{{ ic_volumename }}"
    slave_host: "{{ groups.SC_MASTERNODE.0 }}"
    slave_volume_name: "{{ sc_volumename }}"

  tasks:
  - name: stop the geo-rep
    glustergeorep: command=stop master_volume_name={{ master_volume_name }} slave_host={{ slave_host }} slave_volume_name={{ slave_volume_name }}
    ignore_errors: yes

  - name: delete the geo-rep
    glustergeorep: command=delete master_volume_name={{ master_volume_name }} slave_host={{ slave_host }} slave_volume_name={{ slave_volume_name }}
    ignore_errors: yes


- hosts: MC_MASTERNODE
  gather_facts: no
  remote_user: root

  vars_files:
    - "{{ varfile }}"

  vars:
    master_volume_name: "{{ mc_volumename }}"
    slave_host: "{{ groups.IC_MASTERNODE.0 }}"
    slave_volume_name: "{{ ic_volumename }}"
    
  tasks:
  - name: stop the geo-rep
    glustergeorep: command=stop master_volume_name={{ master_volume_name }} slave_host={{ slave_host }} slave_volume_name={{ slave_volume_name }}
    ignore_errors: yes

  - name: delete the geo-rep
    glustergeorep: command=delete master_volume_name={{ master_volume_name }} slave_host={{ slave_host }} slave_volume_name={{ slave_volume_name }}
    ignore_errors: yes


# DESTROY THE MASTER CLUSTER
- hosts: MC_MASTERNODE
  gather_facts: no
  remote_user: root

  vars_files:
    - "{{ varfile }}"

  tasks:
  - name: stop volumes
    glustervolume: command=stop name="{{ mc_volumename }}"
    ignore_errors: yes

  - name: delete volumes
    glustervolume: command=delete name="{{ mc_volumename }}"
    ignore_errors: yes

  - name: detach peers
    glusterpeer: command=detach name={{ item }}
    with_items:  groups['MC_PEERS']
    ignore_errors: yes


# DESTROY THE INTER CLUSTER
- hosts: IC_MASTERNODE
  gather_facts: no
  remote_user: root

  vars_files:
    - "{{ varfile }}"

  tasks:
  - name: stop volumes
    glustervolume: command=stop name="{{ ic_volumename }}"
    ignore_errors: yes

  - name: delete volumes
    glustervolume: command=delete name="{{ ic_volumename }}"
    ignore_errors: yes

  - name: detach peers
    glusterpeer: command=detach name={{ item }}
    with_items:  groups['IC_PEERS']
    ignore_errors: yes


# DESTROY THE SLAVE CLUSTER
- hosts: SC_MASTERNODE
  gather_facts: no
  remote_user: root

  vars_files:
    - "{{ varfile }}"

  tasks:
  - name: stop volumes
    glustervolume: command=stop name="{{ sc_volumename }}"
    ignore_errors: yes

  - name: delete volumes
    glustervolume: command=delete name="{{ sc_volumename }}"
    ignore_errors: yes

  - name: detach peers
    glusterpeer: command=detach name={{ item }}
    with_items:  groups['SC_PEERS']
    ignore_errors: yes


- hosts: NODES
  gather_facts: no
  remote_user: root

  vars_files:
    - "{{ varfile }}"

  vars:
    vgname_prefix: vg_gluster
    poolname_prefix: lv_pool
    lvname_prefix: lv_brick
    fslabel_prefix: brick
    mountpoint_prefix: "/bricks/fs_gluster"
    brickname: brick


# DESTROY THE BRICKS
  tasks:
  - name: auto destroy bricks
    glusterbrick: command=autodestroy vgname={{ vgname_prefix }} poolname={{ poolname_prefix }} lvname={{ lvname_prefix }} fslabel={{ fslabel_prefix }} mountpoint={{ mountpoint_prefix }} brickname={{ brickname }}
    register: num_bricks
    ignore_errors: yes
    tags:
      autodestroy_bricks


  # TUNED-ADM PROFILE
  - name: set tuned-adm profile
    shell: "tuned-adm profile default"
    when: skip_tuning is not defined
    ignore_errors: yes
    tags:
    - tuned-adm_profile_default


  # CONFIGURE SAMBA
  # TODO: ansiblefy these
  - name: chkconfig off samba
    service: name=smb enabled=no
    when: skip_samba is not defined
    ignore_errors: yes
    tags:
    - deconfig_samba

  - name: stop samba service
    service: name=smb state=stopped
    ignore_errors: yes
    when: skip_samba is not defined
    tags:
    - deconfig_samba

# TODO: add some logic to scramble root passwd or remove non-root user
  - name: deconfig samba user/pass
    shell: (echo "lkjsldedljsldj"; echo "lkjsldedljsldj" ) | smbpasswd -as {{ smb_user }}
    ignore_errors: yes
    when: skip_samba is not defined
    tags:
    - deconfig_samba


# REMOVE THE PEM FILES
  - name: remove pem files
#    file: path=/var/lib/glusterd/geo-replication/*pem* state=absent
    shell: 'rm -f /var/lib/glusterd/geo-replication/*pem*'
    ignore_errors: yes
    tags:
      remove_pemfiles


